platform :ios, '13.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :podspec => '../node_modules/@capacitor/ios/CapacitorCordova.podspec', :platforms => { :ios => '13.0' }
end

target 'PluginTests' do
  use_frameworks!

  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
end
